# coding: utf-8

from __future__ import absolute_import

from datetime import date, datetime  # noqa: F401
from typing import Dict, List  # noqa: F401

from swagger_server import util
from swagger_server.models.base_model_ import Model


class Certificate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, mtime: datetime = None, cert: str = None, fullchain: str = None, privkey: str = None):  # noqa: E501
        """Certificate - a model defined in Swagger

        :param mtime: The mtime of this Certificate.  # noqa: E501
        :type mtime: datetime
        :param cert: The cert of this Certificate.  # noqa: E501
        :type cert: str
        :param fullchain: The fullchain of this Certificate.  # noqa: E501
        :type fullchain: str
        :param privkey: The privkey of this Certificate.  # noqa: E501
        :type privkey: str
        """
        self.swagger_types = {
            'mtime': datetime,
            'cert': str,
            'fullchain': str,
            'privkey': str
        }

        self.attribute_map = {
            'mtime': 'mtime',
            'cert': 'cert',
            'fullchain': 'fullchain',
            'privkey': 'privkey'
        }
        self._mtime = mtime
        self._cert = cert
        self._fullchain = fullchain
        self._privkey = privkey

    @classmethod
    def from_dict(cls, dikt) -> 'Certificate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Certificate of this Certificate.  # noqa: E501
        :rtype: Certificate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mtime(self) -> datetime:
        """Gets the mtime of this Certificate.

        証明書を取得/更新した日時  # noqa: E501

        :return: The mtime of this Certificate.
        :rtype: datetime
        """
        return self._mtime

    @mtime.setter
    def mtime(self, mtime: datetime):
        """Sets the mtime of this Certificate.

        証明書を取得/更新した日時  # noqa: E501

        :param mtime: The mtime of this Certificate.
        :type mtime: datetime
        """

        self._mtime = mtime

    @property
    def cert(self) -> str:
        """Gets the cert of this Certificate.

        サーバ証明書  # noqa: E501

        :return: The cert of this Certificate.
        :rtype: str
        """
        return self._cert

    @cert.setter
    def cert(self, cert: str):
        """Sets the cert of this Certificate.

        サーバ証明書  # noqa: E501

        :param cert: The cert of this Certificate.
        :type cert: str
        """

        self._cert = cert

    @property
    def fullchain(self) -> str:
        """Gets the fullchain of this Certificate.

        中間証明書付きサーバ証明書  # noqa: E501

        :return: The fullchain of this Certificate.
        :rtype: str
        """
        return self._fullchain

    @fullchain.setter
    def fullchain(self, fullchain: str):
        """Sets the fullchain of this Certificate.

        中間証明書付きサーバ証明書  # noqa: E501

        :param fullchain: The fullchain of this Certificate.
        :type fullchain: str
        """

        self._fullchain = fullchain

    @property
    def privkey(self) -> str:
        """Gets the privkey of this Certificate.

        秘密鍵  # noqa: E501

        :return: The privkey of this Certificate.
        :rtype: str
        """
        return self._privkey

    @privkey.setter
    def privkey(self, privkey: str):
        """Sets the privkey of this Certificate.

        秘密鍵  # noqa: E501

        :param privkey: The privkey of this Certificate.
        :type privkey: str
        """

        self._privkey = privkey
