# coding: utf-8

"""
    REST powerdns certbot

    Get a server certificate by let's encrypt and distribute. It will be certified by let's encrypt by connecting PowerDNS API defined in environment variable CERTBOT_PDNS_BASE_URL using environment variable CERTBOT_PDNS_API_KEY. It creates let's encrypt account using e-mail address defined in environment variable CERTBOT_EMAIL. When renew API is called, it renew certificate.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: mitsuru@procube.jp
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.renew_certificate_api import RenewCertificateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRenewCertificateApi(unittest.TestCase):
    """RenewCertificateApi unit test stubs"""

    def setUp(self):
        self.api = api.renew_certificate_api.RenewCertificateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_renew(self):
        """Test case for renew

        renew server certificate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
